name: accs24_figgen
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.7.3
  - numpy=1.24.4
  - python=3.10
  - Pillow=9.2.0
  - pip=23.3.1
  - pip:
      - bokeh==2.4.3
      - flowkit==1.0.1
      - aicsimageio==4.14.0
